<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <RootNamespace>LiveGardenTVPlus</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>Themes\logo-garden.ico</ApplicationIcon>
        <Copyright>@Lululla 2026</Copyright>
        <StartupObject>LiveGardenTVPlus.App</StartupObject>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <Title>LiveGardenTVPlus</Title>
        <AssemblyVersion>2.3</AssemblyVersion>
        <FileVersion>2.3</FileVersion>
        <RepositoryUrl>https://github.com/OwnerPlugins/LiveGardenTVPlus</RepositoryUrl>
        <NeutralLanguage>en</NeutralLanguage>
        <IncludeSymbols>False</IncludeSymbols>
        <PackageReadmeFile>README_VS.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <Platforms>AnyCPU;x86</Platforms>
    </PropertyGroup>
    <ItemGroup>
        <Compile Remove="Controls\**" />
        <EmbeddedResource Remove="Controls\**" />
        <None Remove="Controls\**" />
        <Page Remove="Controls\**" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="Themes\logo-garden.ico">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
        <Content Include="Languages\*.lng">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
      <None Remove="Themes\avatar.gif" />
      <None Remove="Themes\folder.png" />
      <None Remove="Themes\logo-garden.png" />
      <None Remove="Views\avatar.gif" />
      <None Remove="Views\logo-garden.png" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="GTranslate" Version="2.3.1" />
        <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
        <PackageReference Include="XmlTvSharp" Version="1.1.2" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="PlayerHost\player.html">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
      <Resource Include="Themes\avatar.gif">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Themes\folder.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Themes\logo-garden.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Views\avatar.gif" />
      <Resource Include="Views\logo-garden.png" />
    </ItemGroup>
    <ItemGroup>
      <None Update="LICENSE">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Update="README_VS.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>
    <ItemGroup>
      <Page Update="Views\LogoPickerWindow.xaml">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </Page>
    </ItemGroup>
</Project>